[tox]
envlist =
    py{310,311,312,313}-django{42,50,51,52}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = email_editor.test_settings

allowlist_externals = echo

deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6.0
    coverage
    bleach
    bleach[css]

commands =
    coverage run manage.py test {posargs:email_editor}
    coverage report

[coverage:run]
include = email_editor*